# -*- coding: utf-8 -*-
"""RESEARCH_PAPER_RAG_USING _SLM_FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_OyQz_J4xnRklePoLPA-EFNqT5OhkMVX

# INSTALL Liabraries
"""

!pip install -q langchain
!pip install -q langchain-community
!pip install -q chromadb
!pip install -q sentence-transformers
!pip install -q transformers
!pip install -q accelerate
!pip install -q pypdf
!pip install -q torch
!pip install -q langchain-text-splitters

"""UPLOAD RESEARCH PAPERS"""

from google.colab import files

uploaded = files.upload()

"""# Load pdfs"""

import os

print(os.listdir())

import os
from langchain_community.document_loaders import PyPDFLoader

documents = []

pdf_files = [f for f in os.listdir() if f.endswith(".pdf")]

print("PDF Files Found:")
print(pdf_files)

for pdf in pdf_files:
    loader = PyPDFLoader(pdf)

    pages = loader.load()

    print(f"{pdf} --> {len(pages)} pages")

    documents.extend(pages)

print("\nTotal Pages Loaded:", len(documents))

"""# verify text extraction"""

print(documents[0].page_content[:1000])

"""# PREPROCESSING OF DATA"""

import re

for doc in documents:

    text = doc.page_content

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text)

    # Remove citations like [1], [2]
    text = re.sub(r'\[\d+\]', '', text)

    doc.page_content = text

print("Preprocessing Completed!")

"""# verify file name"""

import os

print(os.listdir())

"""# Chunking"""

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=100
)

chunks = splitter.split_documents(documents)

print("Chunks:", len(chunks))

print(chunks[0].page_content)

"""Create embeddings"""

from langchain_community.embeddings import HuggingFaceEmbeddings


embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

print("Embedding model ready")

"""Store embeddings in ChromaDB"""

from langchain_community.vectorstores import Chroma


vector_db = Chroma.from_documents(
    documents=chunks,
    embedding=embedding_model,
    persist_directory="./research_db"
)

print("Vector database created")

vector_db.persist()

print("Research DB Saved Successfully")

print(vector_db._collection.count())

retriever = vector_db.as_retriever(
    search_kwargs={
        "k": 10
    }
)

print("Retriever created")

question = "Explain Retrieval Augmented Generation"

docs = retriever.invoke(question)

for i, doc in enumerate(docs):
    print("\n--- Result", i+1, "---")
    print(doc.page_content[:500])

"""libraries for Gemma SLM"""

!pip install -q bitsandbytes
!pip install -q huggingface_hub

from huggingface_hub import login

login()

from huggingface_hub import whoami

print(whoami())

"""Load Gemma 2B model"""

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch


model_name = "google/gemma-2b-it"


tokenizer = AutoTokenizer.from_pretrained(
    model_name
)


model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16
)


print("Gemma 2B loaded")

import shutil

shutil.make_archive("research_db", "zip", "research_db")

print("ZIP created successfully!")

from google.colab import files

files.download("research_db.zip")

"""Create RAG answer function"""

# def ask_rag(question):

#     # retrieve documents
#     docs = retriever.invoke(question)

#     context = "\n\n".join(
#         [doc.page_content for doc in docs]
#     )


#     prompt = f"""
# You are a research assistant.

# Answer the question using only the context.

# Context:
# {context}


# Question:
# {question}


# Answer:
# """


#     inputs = tokenizer(
#     prompt,
#     return_tensors="pt"
# ).to(model.device)


#     output = model.generate(
#         **inputs,
#         max_new_tokens=300
#     )


#     answer = tokenizer.decode(
#         output[0],
#         skip_special_tokens=True
#     )

#     return answer
def ask_rag(question):

    # Retrieve relevant chunks
    docs = retriever.invoke(question)

    context = "\n\n".join(
        [doc.page_content for doc in docs]
    )

    prompt = f"""
You are an expert research assistant.

Answer the question based on the provided context.
Give a concise and clear answer.

Context:
{context}

Question:
{question}

Answer:
"""

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=2048
    ).to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=150,
        temperature=0.2,
        do_sample=False
    )

    answer = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )

    # Remove prompt from output
    answer = answer.split("Answer:")[-1].strip()

    return answer

print(
    ask_rag(
        "What are the three stages of RAG?"
    )
)

import torch

print(torch.cuda.is_available())

"""Research Q/A RAG"""

answer = ask_rag(
    "Explain the main idea of Retrieval Augmented Generation"
)

print(answer)

"""Source Citation"""

query = "How does FLARE work?"

docs = retriever.invoke(query)

for doc in docs:
    print(doc.metadata)

print(ask_rag("What is RAG?"))

docs = retriever.invoke("What is RAG?")

for i, doc in enumerate(docs):
    print(f"\n------ Chunk {i+1} ------\n")
    print(doc.page_content[:1000])

"""Streamlit Ui"""

!pip install streamlit
!pip install pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile rag.py
# from transformers import AutoTokenizer, AutoModelForCausalLM
# from transformers import pipeline
# import torch
# 
# # Load model only once
# model_name = "google/gemma-2b-it"
# 
# tokenizer = AutoTokenizer.from_pretrained(model_name)
# 
# model = AutoModelForCausalLM.from_pretrained(
#     model_name,
#     torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
#     device_map="auto"
# )
# 
# generator = pipeline(
#     "text-generation",
#     model=model,
#     tokenizer=tokenizer,
#     max_new_tokens=256,
#     temperature=0.3
# )
# from langchain_community.embeddings import HuggingFaceEmbeddings
# from langchain_community.vectorstores import Chroma
# 
# embedding_model = HuggingFaceEmbeddings(
#     model_name="sentence-transformers/all-MiniLM-L6-v2"
# )
# 
# vectorstore = Chroma(
#     persist_directory="./research_db",
#     embedding_function=embedding_model
# )
# 
# retriever = vectorstore.as_retriever(
#     search_kwargs={"k": 10}
# )
# 
# print("Retriever created")
# 
# # retriever should already be created above
# # retriever = ...
# 
# def ask_rag(question):
# 
#     # Retrieve relevant chunks
#     docs = retriever.invoke(question)
# 
#     context = "\n\n".join(
#         [doc.page_content for doc in docs]
#     )
# 
#     prompt = f"""
# You are an expert research assistant.
# 
# Answer the question based on the provided context.
# Give a concise and clear answer.
# 
# Context:
# {context}
# 
# Question:
# {question}
# 
# Answer:
# """
# 
#     inputs = tokenizer(
#         prompt,
#         return_tensors="pt",
#         truncation=True,
#         max_length=2048
#     ).to(model.device)
# 
#     outputs = model.generate(
#         **inputs,
#         max_new_tokens=150,
#         temperature=0.2,
#         do_sample=False
#     )
# 
#     answer = tokenizer.decode(
#         outputs[0],
#         skip_special_tokens=True
#     )
# 
#     # Remove prompt from output
#     answer = answer.split("Answer:")[-1].strip()
# 
#     return answer
# print(
#     ask_rag(
#         "What are the three stages of RAG?"
#     )
# )

"""Create app.py"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# from rag import ask_rag      # Import the function from rag.py
# 
# # ---------------- Page Configuration ----------------
# st.set_page_config(
#     page_title="Research Paper QA System",
#     page_icon="📚",
#     layout="wide"
# )
# 
# # ---------------- Title ----------------
# st.title("📚 Research Paper Question Answering System")
# st.write("Ask questions about the uploaded research papers using RAG + Gemma 2B.")
# 
# # ---------------- User Input ----------------
# question = st.text_input(
#     "Enter your question:",
#     placeholder="Example: What is Retrieval-Augmented Generation?"
# )
# 
# # ---------------- Generate Button ----------------
# if st.button("Generate Answer"):
# 
#     if question.strip() == "":
#         st.warning("Please enter a question.")
#     else:
#         with st.spinner("Generating answer..."):
# 
#             try:
#                 answer = ask_rag(question)
# 
#                 st.subheader("Answer")
#                 st.success(answer)
# 
#             except Exception as e:
#                 st.error(f"Error: {e}")

"""verifying  app.py file"""

!cat app.py

"""Start Streamlit"""

!streamlit run app.py &>/content/logs.txt &

"""LocalTunnel install"""

!npm install -g localtunnel

"""Public URL generate"""

# !lt --port 8501

!cat logs.txt

!ps -ef | grep streamlit

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

!streamlit run app.py --server.port 8501 > logs.txt 2>&1 &

!npm install -g localtunnel

!cloudflared tunnel --url http://localhost:8501

!ps -ef | grep streamlit

"""uploading on git"""

